//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHMSoap.SerSalarie {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salarie", Namespace="http://schemas.datacontract.org/2004/07/AccesDonnees")]
    [System.SerializableAttribute()]
    public partial class Salarie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deptno {
            get {
                return this.DeptnoField;
            }
            set {
                if ((this.DeptnoField.Equals(value) != true)) {
                    this.DeptnoField = value;
                    this.RaisePropertyChanged("Deptno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dname {
            get {
                return this.DnameField;
            }
            set {
                if ((object.ReferenceEquals(this.DnameField, value) != true)) {
                    this.DnameField = value;
                    this.RaisePropertyChanged("Dname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empno {
            get {
                return this.EmpnoField;
            }
            set {
                if ((this.EmpnoField.Equals(value) != true)) {
                    this.EmpnoField = value;
                    this.RaisePropertyChanged("Empno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ename {
            get {
                return this.EnameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnameField, value) != true)) {
                    this.EnameField = value;
                    this.RaisePropertyChanged("Ename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sal {
            get {
                return this.SalField;
            }
            set {
                if ((this.SalField.Equals(value) != true)) {
                    this.SalField = value;
                    this.RaisePropertyChanged("Sal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerSalarie.ISalaries")]
    public interface ISalaries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmpById", ReplyAction="http://tempuri.org/ISalaries/GetEmpByIdResponse")]
        IHMSoap.SerSalarie.Salarie GetEmpById(int empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmpById", ReplyAction="http://tempuri.org/ISalaries/GetEmpByIdResponse")]
        System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie> GetEmpByIdAsync(int empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmps", ReplyAction="http://tempuri.org/ISalaries/GetEmpsResponse")]
        IHMSoap.SerSalarie.Salarie[] GetEmps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmps", ReplyAction="http://tempuri.org/ISalaries/GetEmpsResponse")]
        System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie[]> GetEmpsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmpsByDeptno", ReplyAction="http://tempuri.org/ISalaries/GetEmpsByDeptnoResponse")]
        IHMSoap.SerSalarie.Salarie[] GetEmpsByDeptno(int deptno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaries/GetEmpsByDeptno", ReplyAction="http://tempuri.org/ISalaries/GetEmpsByDeptnoResponse")]
        System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie[]> GetEmpsByDeptnoAsync(int deptno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalariesChannel : IHMSoap.SerSalarie.ISalaries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalariesClient : System.ServiceModel.ClientBase<IHMSoap.SerSalarie.ISalaries>, IHMSoap.SerSalarie.ISalaries {
        
        public SalariesClient() {
        }
        
        public SalariesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalariesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalariesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalariesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IHMSoap.SerSalarie.Salarie GetEmpById(int empno) {
            return base.Channel.GetEmpById(empno);
        }
        
        public System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie> GetEmpByIdAsync(int empno) {
            return base.Channel.GetEmpByIdAsync(empno);
        }
        
        public IHMSoap.SerSalarie.Salarie[] GetEmps() {
            return base.Channel.GetEmps();
        }
        
        public System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie[]> GetEmpsAsync() {
            return base.Channel.GetEmpsAsync();
        }
        
        public IHMSoap.SerSalarie.Salarie[] GetEmpsByDeptno(int deptno) {
            return base.Channel.GetEmpsByDeptno(deptno);
        }
        
        public System.Threading.Tasks.Task<IHMSoap.SerSalarie.Salarie[]> GetEmpsByDeptnoAsync(int deptno) {
            return base.Channel.GetEmpsByDeptnoAsync(deptno);
        }
    }
}
